#!/usr/bin/env bash
# installs nginx
# print "Hello World"

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello world" > /var/www/html/index.html
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
