#!/usr/bin/env bash
#I just replaced the conf with the default one
mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
sudo service nginx restart
