#!/usr/bin/env bash
# this gustavo scripting

deletor() {
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && deletor' SIGTERM
	trap 'deletor' SIGQUIT
done
